package com.telecom.scm.security.service;

import java.util.Collection;
import java.util.Comparator;
import java.util.List;
import java.util.Set;

import com.telecom.scm.common.enums.MenuTypeEnum;
import com.telecom.scm.security.dto.response.CurrentUserMenuItem;

public final class PermissionMenuCatalog {

    private static final Comparator<MenuDefinition> MENU_SORTER =
            Comparator.comparing(MenuDefinition::parentId)
                    .thenComparing(MenuDefinition::sortNo)
                    .thenComparing(MenuDefinition::id);

    private static final List<MenuDefinition> MENU_DEFINITIONS =
            List.of(
                    new MenuDefinition(
                            101L,
                            0L,
                            "平台总览",
                            "MENU",
                            "/admin/dashboard",
                            "pages/admin/AdminDashboardPage",
                            "admin:dashboard:view",
                            "DashboardOutlined",
                            1,
                            true,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            102L,
                            0L,
                            "用户管理",
                            "MENU",
                            "/admin/users",
                            "pages/admin/AdminUsersPage",
                            "admin:user:view",
                            "UserOutlined",
                            2,
                            true,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            103L,
                            0L,
                            "角色管理",
                            "MENU",
                            "/admin/roles",
                            "pages/admin/AdminGovernancePage",
                            "admin:role:view",
                            "SafetyOutlined",
                            3,
                            true,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            112L,
                            0L,
                            "会员等级",
                            "MENU",
                            "/admin/customer-levels",
                            "pages/admin/AdminCustomerLevelsPage",
                            "admin:customer-level:view",
                            "ClusterOutlined",
                            4,
                            true,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            116L,
                            0L,
                            "品牌管理",
                            "MENU",
                            "/admin/brands",
                            "pages/admin/AdminBrandsPage",
                            "admin:product:view",
                            "ShopOutlined",
                            5,
                            true,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            117L,
                            0L,
                            "分类管理",
                            "MENU",
                            "/admin/categories",
                            "pages/admin/AdminCategoriesPage",
                            "admin:product:view",
                            "AppstoreOutlined",
                            6,
                            true,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            118L,
                            116L,
                            "新建品牌",
                            "BUTTON",
                            null,
                            null,
                            "admin:product:edit",
                            null,
                            1,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            119L,
                            116L,
                            "编辑品牌",
                            "BUTTON",
                            null,
                            null,
                            "admin:product:edit",
                            null,
                            2,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            120L,
                            116L,
                            "删除品牌",
                            "BUTTON",
                            null,
                            null,
                            "admin:product:edit",
                            null,
                            3,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            121L,
                            117L,
                            "新建分类",
                            "BUTTON",
                            null,
                            null,
                            "admin:product:edit",
                            null,
                            1,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            122L,
                            117L,
                            "编辑分类",
                            "BUTTON",
                            null,
                            null,
                            "admin:product:edit",
                            null,
                            2,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            123L,
                            117L,
                            "删除分类",
                            "BUTTON",
                            null,
                            null,
                            "admin:product:edit",
                            null,
                            3,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            114L,
                            0L,
                            "注册审核",
                            "MENU",
                            "/admin/registrations",
                            "pages/admin/AdminRegistrationsPage",
                            "admin:registration:view",
                            "SafetyOutlined",
                            7,
                            true,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            104L,
                            0L,
                            "菜单权限",
                            "MENU",
                            "/admin/menus",
                            "pages/admin/AdminGovernancePage",
                            "admin:menu:view",
                            "PartitionOutlined",
                            8,
                            true,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            105L,
                            0L,
                            "登录日志",
                            "MENU",
                            "/admin/login-log",
                            "pages/admin/AdminGovernancePage",
                            "admin:login-log:view",
                            "FileSearchOutlined",
                            9,
                            true,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            106L,
                            0L,
                            "操作日志",
                            "MENU",
                            "/admin/operation-log",
                            "pages/admin/AdminGovernancePage",
                            "admin:operation-log:view",
                            "FileSearchOutlined",
                            10,
                            true,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            107L,
                            0L,
                            "导入导出",
                            "MENU",
                            "/admin/import-export",
                            "pages/admin/AdminGovernancePage",
                            "admin:transfer:view",
                            "ToolOutlined",
                            11,
                            true,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            108L,
                            107L,
                            "执行导入",
                            "BUTTON",
                            null,
                            null,
                            "admin:import:run",
                            null,
                            1,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            109L,
                            107L,
                            "执行导出",
                            "BUTTON",
                            null,
                            null,
                            "admin:export:view",
                            null,
                            2,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            110L,
                            103L,
                            "分配用户角色",
                            "BUTTON",
                            null,
                            null,
                            "admin:role:assign",
                            null,
                            1,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            113L,
                            112L,
                            "保存等级配置",
                            "BUTTON",
                            null,
                            null,
                            "admin:customer-level:edit",
                            null,
                            1,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            115L,
                            114L,
                            "审核注册申请",
                            "BUTTON",
                            null,
                            null,
                            "admin:registration:review",
                            null,
                            1,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            111L,
                            104L,
                            "分配角色菜单",
                            "BUTTON",
                            null,
                            null,
                            "admin:menu:assign",
                            null,
                            1,
                            false,
                            List.of("ADMIN")),
                    new MenuDefinition(
                            201L,
                            0L,
                            "客户总览",
                            "MENU",
                            "/member/customer/dashboard",
                            "pages/member/customer/CustomerDashboardPage",
                            "customer:dashboard:view",
                            "DashboardOutlined",
                            1,
                            true,
                            List.of("CUSTOMER")),
                    new MenuDefinition(
                            202L,
                            0L,
                            "客户资料",
                            "MENU",
                            "/member/customer/profile",
                            "pages/member/customer/CustomerWorkspacePage",
                            "customer:profile:view",
                            "ProfileOutlined",
                            2,
                            true,
                            List.of("CUSTOMER")),
                    new MenuDefinition(
                            203L,
                            0L,
                            "我的订单",
                            "MENU",
                            "/member/customer/orders",
                            "pages/member/customer/CustomerOrdersPage",
                            "customer:order:view",
                            "ShoppingCartOutlined",
                            3,
                            true,
                            List.of("CUSTOMER")),
                    new MenuDefinition(
                            204L,
                            0L,
                            "售后服务",
                            "MENU",
                            "/member/customer/aftersale",
                            "pages/member/customer/CustomerAftersalePage",
                            "customer:aftersale:view",
                            "TruckOutlined",
                            4,
                            true,
                            List.of("CUSTOMER")),
                    new MenuDefinition(
                            205L,
                            0L,
                            "积分账户",
                            "MENU",
                            "/member/customer/points",
                            "pages/member/customer/CustomerPointsPage",
                            "customer:point:view",
                            "GiftOutlined",
                            5,
                            true,
                            List.of("CUSTOMER")),
                    new MenuDefinition(
                            206L,
                            0L,
                            "推荐关系",
                            "MENU",
                            "/member/customer/referral",
                            "pages/member/customer/CustomerWorkspacePage",
                            "customer:referral:view",
                            "UsergroupAddOutlined",
                            6,
                            true,
                            List.of("CUSTOMER")),
                    new MenuDefinition(
                            301L,
                            0L,
                            "商家总览",
                            "MENU",
                            "/member/merchant/dashboard",
                            "pages/member/merchant/MerchantDashboardPage",
                            "merchant:dashboard:view",
                            "DashboardOutlined",
                            1,
                            true,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            302L,
                            0L,
                            "商家档案",
                            "MENU",
                            "/member/merchant/profile",
                            "pages/member/merchant/MerchantProfilePage",
                            "merchant:profile:view",
                            "ProfileOutlined",
                            2,
                            true,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            303L,
                            0L,
                            "商品管理",
                            "MENU",
                            "/member/merchant/goods",
                            "pages/member/merchant/MerchantGoodsPage",
                            "merchant:goods:view",
                            "ShopOutlined",
                            3,
                            true,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            304L,
                            0L,
                            "会员折扣",
                            "MENU",
                            "/member/merchant/pricing/level",
                            "pages/member/merchant/MerchantPricingPage",
                            "merchant:pricing:level:view",
                            "GiftOutlined",
                            4,
                            true,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            305L,
                            0L,
                            "客户专属价",
                            "MENU",
                            "/member/merchant/pricing/customer",
                            "pages/member/merchant/MerchantPricingPage",
                            "merchant:pricing:customer:view",
                            "UsergroupAddOutlined",
                            5,
                            true,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            306L,
                            0L,
                            "订单处理",
                            "MENU",
                            "/member/merchant/orders",
                            "pages/member/merchant/MerchantOrdersPage",
                            "merchant:order:view",
                            "ShoppingCartOutlined",
                            6,
                            true,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            307L,
                            0L,
                            "发货物流",
                            "MENU",
                            "/member/merchant/shipping",
                            "pages/member/merchant/MerchantShippingPage",
                            "merchant:order:ship",
                            "TruckOutlined",
                            7,
                            true,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            308L,
                            0L,
                            "售后处理",
                            "MENU",
                            "/member/merchant/aftersale",
                            "pages/member/merchant/MerchantAftersalePage",
                            "merchant:aftersale:view",
                            "ProfileOutlined",
                            8,
                            true,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            309L,
                            0L,
                            "经营报表",
                            "MENU",
                            "/member/merchant/reports/product",
                            "pages/member/merchant/MerchantReportsPage",
                            "merchant:report:view",
                            "LineChartOutlined",
                            9,
                            true,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            320L,
                            303L,
                            "编辑商品",
                            "BUTTON",
                            null,
                            null,
                            "merchant:goods:edit",
                            null,
                            1,
                            false,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            325L,
                            303L,
                            "查看成本价",
                            "BUTTON",
                            null,
                            null,
                            "merchant:cost:view",
                            null,
                            2,
                            false,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            327L,
                            303L,
                            "商品授权",
                            "MENU",
                            "/member/merchant/goods/auth",
                            "pages/member/merchant/MerchantPricingPage",
                            "merchant:pricing:level:view",
                            "SafetyOutlined",
                            3,
                            false,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            321L,
                            306L,
                            "审核订单",
                            "BUTTON",
                            null,
                            null,
                            "merchant:order:approve",
                            null,
                            1,
                            false,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            322L,
                            308L,
                            "同意售后",
                            "BUTTON",
                            null,
                            null,
                            "merchant:aftersale:approve",
                            null,
                            1,
                            false,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            323L,
                            308L,
                            "驳回售后",
                            "BUTTON",
                            null,
                            null,
                            "merchant:aftersale:reject",
                            null,
                            2,
                            false,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            324L,
                            308L,
                            "执行退款",
                            "BUTTON",
                            null,
                            null,
                            "merchant:aftersale:refund",
                            null,
                            3,
                            false,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            326L,
                            309L,
                            "查看利润",
                            "BUTTON",
                            null,
                            null,
                            "merchant:profit:view",
                            null,
                            1,
                            false,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            328L,
                            309L,
                            "订单报表",
                            "MENU",
                            "/member/merchant/reports/order",
                            "pages/member/merchant/MerchantReportsPage",
                            "merchant:report:view",
                            "LineChartOutlined",
                            2,
                            false,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            329L,
                            309L,
                            "客户报表",
                            "MENU",
                            "/member/merchant/reports/customer",
                            "pages/member/merchant/MerchantReportsPage",
                            "merchant:report:view",
                            "LineChartOutlined",
                            3,
                            false,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            331L,
                            309L,
                            "导出报表",
                            "BUTTON",
                            null,
                            null,
                            "merchant:report:export",
                            null,
                            4,
                            false,
                            List.of("MERCHANT")),
                    new MenuDefinition(
                            401L,
                            0L,
                            "供应总览",
                            "MENU",
                            "/member/supplier/dashboard",
                            "pages/member/supplier/SupplierDashboardPage",
                            "supplier:dashboard:view",
                            "DashboardOutlined",
                            1,
                            true,
                            List.of("SUPPLIER")),
                    new MenuDefinition(
                            402L,
                            0L,
                            "供应商资料",
                            "MENU",
                            "/member/supplier/profile",
                            "pages/member/supplier/SupplierWorkspacePage",
                            "supplier:profile:view",
                            "ProfileOutlined",
                            2,
                            true,
                            List.of("SUPPLIER")),
                    new MenuDefinition(
                            403L,
                            0L,
                            "商品档案",
                            "MENU",
                            "/member/supplier/products",
                            "pages/member/supplier/SupplierProductsPage",
                            "supplier:product:view",
                            "ShopOutlined",
                            3,
                            true,
                            List.of("SUPPLIER")),
                    new MenuDefinition(
                            404L,
                            0L,
                            "库存台账",
                            "MENU",
                            "/member/supplier/stock",
                            "pages/member/supplier/SupplierWorkspacePage",
                            "supplier:stock:view",
                            "TruckOutlined",
                            4,
                            true,
                            List.of("SUPPLIER")),
                    new MenuDefinition(
                            408L,
                            0L,
                            "合作关系",
                            "MENU",
                            "/member/supplier/cooperation/relations",
                            "pages/member/supplier/SupplierCooperationPage",
                            "supplier:cooperation:view",
                            "UserOutlined",
                            5,
                            true,
                            List.of("SUPPLIER")),
                    new MenuDefinition(
                            409L,
                            0L,
                            "授权商品",
                            "MENU",
                            "/member/supplier/cooperation/authorizations",
                            "pages/member/supplier/SupplierCooperationPage",
                            "supplier:cooperation:view",
                            "SafetyOutlined",
                            6,
                            true,
                            List.of("SUPPLIER")),
                    new MenuDefinition(
                            406L,
                            408L,
                            "维护合作关系",
                            "BUTTON",
                            null,
                            null,
                            "supplier:cooperation:edit",
                            null,
                            1,
                            false,
                            List.of("SUPPLIER")),
                    new MenuDefinition(
                            407L,
                            409L,
                            "维护授权商品",
                            "BUTTON",
                            null,
                            null,
                            "supplier:authorization:edit",
                            null,
                            2,
                            false,
                            List.of("SUPPLIER")));

    private PermissionMenuCatalog() {}

    public static List<MenuDefinition> definitions() {
        return MENU_DEFINITIONS;
    }

    public static List<CurrentUserMenuItem> routeMenusForPermissions(
            Collection<String> permissions) {
        // If permissions is null, include all menus (demo mode)
        if (permissions == null) {
            return MENU_DEFINITIONS.stream()
                    .filter(definition -> MenuTypeEnum.MENU.getCode().equals(definition.menuType()))
                    .filter(definition -> definition.path() != null && !definition.path().isBlank())
                    .sorted(MENU_SORTER)
                    .map(
                            definition ->
                                    new CurrentUserMenuItem(
                                            definition.id(),
                                            definition.parentId(),
                                            definition.menuName(),
                                            definition.path(),
                                            definition.component(),
                                            definition.icon(),
                                            definition.permissionCode(),
                                            definition.sortNo(),
                                            definition.visible()))
                    .toList();
        }
        Set<String> grantedPermissions = Set.copyOf(permissions);
        return MENU_DEFINITIONS.stream()
                .filter(definition -> MenuTypeEnum.MENU.getCode().equals(definition.menuType()))
                .filter(definition -> definition.path() != null && !definition.path().isBlank())
                .filter(
                        definition ->
                                definition.permissionCode() == null
                                        || definition.permissionCode().isBlank()
                                        || grantedPermissions.contains(definition.permissionCode()))
                .sorted(MENU_SORTER)
                .map(
                        definition ->
                                new CurrentUserMenuItem(
                                        definition.id(),
                                        definition.parentId(),
                                        definition.menuName(),
                                        definition.path(),
                                        definition.component(),
                                        definition.icon(),
                                        definition.permissionCode(),
                                        definition.sortNo(),
                                        definition.visible()))
                .toList();
    }

    public record MenuDefinition(
            Long id,
            Long parentId,
            String menuName,
            String menuType,
            String path,
            String component,
            String permissionCode,
            String icon,
            Integer sortNo,
            boolean visible,
            List<String> defaultRoleCodes) {}
}
