-- 初始 baseline 建表脚本
-- 由本地 telecom_supply_chain 数据库导出，包含当前所有业务表结构
-- 注意：flyway_schema_history 和 test_flyway 已移除

CREATE TABLE IF NOT EXISTS `aftersale_audit_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `aftersale_id` bigint unsigned NOT NULL COMMENT '售后单ID',
  `action_type` varchar(30) NOT NULL COMMENT '动作类型',
  `old_status` varchar(30) DEFAULT NULL COMMENT '原状态',
  `new_status` varchar(30) NOT NULL COMMENT '新状态',
  `operator_id` bigint unsigned DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(50) NOT NULL COMMENT '操作人名称',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_aftersale_audit_log_aftersale_id` (`aftersale_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='售后审核日志表';
CREATE TABLE IF NOT EXISTS `aftersale_info` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `aftersale_no` varchar(50) NOT NULL COMMENT '售后单号',
  `order_id` bigint unsigned NOT NULL COMMENT '订单ID',
  `customer_id` bigint unsigned NOT NULL COMMENT '客户ID',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商家ID',
  `aftersale_type` varchar(30) NOT NULL COMMENT '售后类型：REFUND_ONLY/RETURN_REFUND',
  `reason_type` varchar(50) NOT NULL COMMENT '售后原因',
  `reason_desc` varchar(255) DEFAULT NULL COMMENT '原因说明',
  `apply_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '申请金额',
  `approved_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '审核金额',
  `aftersale_status` varchar(30) NOT NULL COMMENT '售后状态',
  `need_return` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否退货',
  `return_tracking_no` varchar(100) DEFAULT NULL COMMENT '退货物流单号',
  `merchant_receive_time` datetime DEFAULT NULL COMMENT '商家收货时间',
  `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_aftersale_info_no` (`aftersale_no`),
  KEY `idx_aftersale_info_order_id` (`order_id`),
  KEY `idx_aftersale_info_customer_id` (`customer_id`),
  KEY `idx_aftersale_info_status` (`aftersale_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='售后主表';
CREATE TABLE IF NOT EXISTS `aftersale_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `aftersale_id` bigint unsigned NOT NULL COMMENT '售后单ID',
  `order_item_id` bigint unsigned NOT NULL COMMENT '订单明细ID',
  `sku_id` bigint unsigned NOT NULL COMMENT 'SKU ID',
  `spu_name` varchar(150) NOT NULL COMMENT 'SPU名称快照',
  `sku_name` varchar(150) NOT NULL COMMENT 'SKU名称快照',
  `spec_text` varchar(255) NOT NULL COMMENT '规格快照',
  `quantity` int NOT NULL COMMENT '售后数量',
  `apply_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '申请金额',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_aftersale_item_aftersale_id` (`aftersale_id`),
  KEY `idx_aftersale_item_order_item_id` (`order_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='售后明细表';
CREATE TABLE IF NOT EXISTS `cart_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `customer_id` bigint unsigned NOT NULL COMMENT '客户ID',
  `merchant_goods_id` bigint unsigned NOT NULL COMMENT '商家商品ID',
  `sku_id` bigint unsigned NOT NULL COMMENT 'SKU ID',
  `quantity` int NOT NULL DEFAULT '1' COMMENT '购买数量',
  `checked_flag` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否选中',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cart_item_customer_goods` (`customer_id`,`merchant_goods_id`),
  KEY `idx_cart_item_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='购物车表';
CREATE TABLE IF NOT EXISTS `customer_info` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `member_id` bigint unsigned NOT NULL COMMENT '会员主体ID',
  `company_name` varchar(150) DEFAULT NULL COMMENT '客户企业名称',
  `member_level` varchar(20) NOT NULL DEFAULT 'NORMAL' COMMENT '会员等级',
  `accumulated_paid_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '累计完成实付金额',
  `last_level_upgrade_at` datetime DEFAULT NULL COMMENT '最近升级时间',
  `contact_name` varchar(50) NOT NULL COMMENT '联系人',
  `contact_phone` varchar(20) NOT NULL COMMENT '联系电话',
  `invoice_title` varchar(150) DEFAULT NULL COMMENT '发票抬头',
  `tax_no` varchar(50) DEFAULT NULL COMMENT '纳税人识别号',
  `bank_name` varchar(100) DEFAULT NULL COMMENT '开户行',
  `bank_account` varchar(50) DEFAULT NULL COMMENT '银行账号',
  `invite_code` varchar(50) DEFAULT NULL COMMENT '邀请码',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `points_balance` int NOT NULL DEFAULT '0' COMMENT '积分余额',
  `accumulated_points` int NOT NULL DEFAULT '0' COMMENT '累计获得积分',
  `used_points` int NOT NULL DEFAULT '0' COMMENT '累计使用积分',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_customer_info_member_id` (`member_id`),
  UNIQUE KEY `uk_customer_info_invite_code` (`invite_code`),
  KEY `idx_customer_info_level` (`member_level`),
  KEY `idx_customer_info_invite_code` (`invite_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户信息表';
CREATE TABLE IF NOT EXISTS `customer_level_config` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `level_code` varchar(20) NOT NULL COMMENT '等级编码',
  `level_name` varchar(50) NOT NULL COMMENT '等级名称',
  `upgrade_threshold_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '升级阈值金额',
  `discount_scope` varchar(30) DEFAULT NULL COMMENT '折扣范围',
  `discount_value` decimal(10,2) DEFAULT NULL COMMENT '折扣值',
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `upgrade_threshold_points` int NOT NULL DEFAULT '0' COMMENT '升级阈值积分',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_customer_level_config_code` (`level_code`),
  KEY `idx_customer_level_config_status` (`status`),
  KEY `idx_customer_level_config_threshold` (`upgrade_threshold_amount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户等级配置表';
CREATE TABLE IF NOT EXISTS `customer_price_rule` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商家ID',
  `customer_id` bigint unsigned NOT NULL COMMENT '客户ID',
  `sku_id` bigint unsigned NOT NULL COMMENT 'SKU ID',
  `special_price` decimal(12,2) NOT NULL COMMENT '客户专属价',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_customer_price_rule` (`merchant_id`,`customer_id`,`sku_id`),
  KEY `idx_customer_price_rule_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户专属价格规则表';
CREATE TABLE IF NOT EXISTS `customer_referral` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `referrer_customer_id` bigint unsigned NOT NULL COMMENT '推荐人客户ID',
  `referred_customer_id` bigint unsigned NOT NULL COMMENT '被推荐客户ID',
  `bind_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '绑定时间',
  `status` varchar(20) NOT NULL DEFAULT 'BOUND' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_customer_referral_referred` (`referred_customer_id`),
  KEY `idx_customer_referral_referrer` (`referrer_customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户转介绍关系表';
CREATE TABLE IF NOT EXISTS `file_storage` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `biz_type` varchar(50) NOT NULL COMMENT '业务类型',
  `biz_id` bigint unsigned DEFAULT NULL COMMENT '业务ID',
  `original_name` varchar(255) NOT NULL COMMENT '原始文件名',
  `storage_name` varchar(255) NOT NULL COMMENT '存储文件名',
  `file_path` varchar(500) NOT NULL COMMENT '文件路径',
  `file_ext` varchar(20) DEFAULT NULL COMMENT '文件扩展名',
  `content_type` varchar(100) DEFAULT NULL COMMENT '文件类型',
  `file_size` bigint unsigned NOT NULL DEFAULT '0' COMMENT '文件大小',
  `uploader_id` bigint unsigned DEFAULT NULL COMMENT '上传人ID',
  `upload_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_file_storage_biz` (`biz_type`,`biz_id`),
  KEY `idx_file_storage_uploader_id` (`uploader_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='统一附件表';
CREATE TABLE IF NOT EXISTS `goods_auth_rule` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商家ID',
  `auth_type` varchar(20) NOT NULL COMMENT '授权类型：BRAND/CATEGORY/PRODUCT',
  `target_id` bigint unsigned NOT NULL COMMENT '目标对象ID',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_goods_auth_rule` (`merchant_id`,`auth_type`,`target_id`),
  KEY `idx_goods_auth_rule_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品授权规则表';
CREATE TABLE IF NOT EXISTS `level_discount_rule` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商家ID',
  `member_level` varchar(20) NOT NULL COMMENT '会员等级',
  `category_id` bigint unsigned NOT NULL COMMENT '分类ID',
  `discount_rate` decimal(5,2) NOT NULL COMMENT '折扣比例，如9.50表示9.5折',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `target_type` varchar(20) NOT NULL DEFAULT 'CATEGORY' COMMENT 'discount target type',
  `target_id` bigint unsigned DEFAULT NULL COMMENT 'discount target id',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_level_discount_rule` (`merchant_id`,`member_level`,`target_type`,`target_id`),
  KEY `idx_level_discount_rule_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='会员等级折扣规则表';
CREATE TABLE IF NOT EXISTS `member_account` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `member_code` varchar(50) NOT NULL COMMENT '会员编码',
  `member_type` varchar(20) NOT NULL COMMENT '会员类型：CUSTOMER/MERCHANT/SUPPLIER',
  `member_name` varchar(100) NOT NULL COMMENT '会员主体名称',
  `phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_member_account_code` (`member_code`),
  KEY `idx_member_account_type` (`member_type`),
  KEY `idx_member_account_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='会员主体基础表';
CREATE TABLE IF NOT EXISTS `member_address` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `member_id` bigint unsigned NOT NULL COMMENT '会员主体ID',
  `address_type` varchar(20) NOT NULL COMMENT '地址类型：RECEIVE/SEND',
  `receiver_name` varchar(50) NOT NULL COMMENT '收件人',
  `receiver_phone` varchar(20) NOT NULL COMMENT '联系电话',
  `province` varchar(50) NOT NULL COMMENT '省份',
  `city` varchar(50) NOT NULL COMMENT '城市',
  `district` varchar(50) NOT NULL COMMENT '区县',
  `detail_address` varchar(255) NOT NULL COMMENT '详细地址',
  `is_default` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否默认地址',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_member_address_member_id` (`member_id`),
  KEY `idx_member_address_default` (`member_id`,`is_default`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='会员地址表';
CREATE TABLE IF NOT EXISTS `merchant_goods` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商家ID',
  `supplier_id` bigint unsigned DEFAULT NULL COMMENT '渚涘簲鍟咺D锛堣嚜钀ュ晢鍝佷负绌猴級',
  `spu_id` bigint unsigned DEFAULT NULL COMMENT '鑷?惀鍟嗗搧SPU ID',
  `source_type` varchar(20) NOT NULL DEFAULT 'SUPPLIER_AUTH' COMMENT '鍟嗗搧鏉ユ簮锛歋UPPLIER_AUTH/DIRECT',
  `main_image_id` bigint unsigned DEFAULT NULL COMMENT '涓诲浘闄勪欢ID',
  `image_ids` json DEFAULT NULL COMMENT '鍥剧墖ID鍒楄〃JSON',
  `keywords` varchar(255) DEFAULT NULL COMMENT '鍏抽敭璇',
  `detail_content` text COMMENT '璇︾粏鎻忚堪',
  `sku_id` bigint unsigned DEFAULT NULL COMMENT 'SKU ID锛堣嚜钀ュ晢鍝佸叧鑱攑roduct_sku_id锛',
  `sale_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '销售价',
  `current_cost_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '当前成本价',
  `rebate_rate` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '返利比例',
  `sale_status` varchar(20) NOT NULL DEFAULT 'OFF' COMMENT '上架状态：ON/OFF',
  `delivery_mode` varchar(20) NOT NULL DEFAULT 'SPOT' COMMENT '浜や粯鏂瑰紡: SPOT=鐜拌揣, PROJECT=椤圭洰浜や粯',
  `stock_qty` int DEFAULT '0',
  `safety_stock` int DEFAULT '0',
  `sale_count` bigint unsigned NOT NULL DEFAULT '0' COMMENT '累计销售量',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `freight_amount` decimal(10,2) DEFAULT '0.00' COMMENT '运费',
  `description` text COMMENT '商品说明',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_goods_merchant_sku` (`merchant_id`,`sku_id`),
  KEY `idx_merchant_goods_supplier_id` (`supplier_id`),
  KEY `idx_merchant_goods_sale_status` (`sale_status`),
  KEY `idx_merchant_goods_sale_count` (`sale_count`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商家销售商品表';
CREATE TABLE IF NOT EXISTS `merchant_info` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `member_id` bigint unsigned NOT NULL COMMENT '会员主体ID',
  `shop_name` varchar(150) NOT NULL COMMENT '店铺名称',
  `license_no` varchar(100) DEFAULT NULL COMMENT '营业执照号',
  `contact_name` varchar(50) NOT NULL COMMENT '联系人',
  `contact_phone` varchar(20) NOT NULL COMMENT '联系电话',
  `shop_desc` text COMMENT '店铺简介',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_info_member_id` (`member_id`),
  KEY `idx_merchant_info_shop_name` (`shop_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商家信息表';
CREATE TABLE IF NOT EXISTS `merchant_supplier_relation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商家ID',
  `supplier_id` bigint unsigned NOT NULL COMMENT '供应商ID',
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '合作状态：ACTIVE/ENDED',
  `cooperation_start_at` datetime DEFAULT NULL COMMENT '合作开始时间',
  `cooperation_end_at` datetime DEFAULT NULL COMMENT '合作结束时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_supplier_relation` (`merchant_id`,`supplier_id`),
  KEY `idx_merchant_supplier_relation_supplier` (`supplier_id`),
  KEY `idx_merchant_supplier_relation_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商家供应商合作关系表';
CREATE TABLE IF NOT EXISTS `order_info` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_no` varchar(50) NOT NULL COMMENT '订单号',
  `customer_id` bigint unsigned NOT NULL COMMENT '客户ID',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商家ID',
  `order_source` varchar(20) NOT NULL DEFAULT 'WEB_MALL',
  `order_status` varchar(30) NOT NULL COMMENT '订单状态',
  `pay_status` varchar(20) NOT NULL DEFAULT 'UNPAID' COMMENT '支付状态',
  `shipment_status` varchar(20) NOT NULL DEFAULT 'WAIT_SHIP' COMMENT '发货状态',
  `aftersale_status` varchar(20) NOT NULL DEFAULT 'NONE' COMMENT '售后状态',
  `goods_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '商品总金额',
  `freight_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '运费',
  `discount_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '优惠金额',
  `used_points` int NOT NULL DEFAULT '0' COMMENT '下单抵扣使用的积分',
  `points_deduction_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '积分抵现金额',
  `pay_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '应付金额',
  `cost_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '成本总额',
  `profit_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '利润总额',
  `pay_method` varchar(30) DEFAULT NULL COMMENT '支付方式',
  `customer_remark` varchar(255) DEFAULT NULL COMMENT '客户备注',
  `receiver_name` varchar(50) NOT NULL COMMENT '收货人',
  `receiver_phone` varchar(20) NOT NULL COMMENT '收货电话',
  `receiver_province` varchar(50) NOT NULL COMMENT '收货省份',
  `receiver_city` varchar(50) NOT NULL COMMENT '收货城市',
  `receiver_district` varchar(50) NOT NULL COMMENT '收货区县',
  `receiver_address` varchar(255) NOT NULL COMMENT '收货详细地址',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_info_order_no` (`order_no`),
  KEY `idx_order_info_customer_time` (`customer_id`,`created_time`),
  KEY `idx_order_info_merchant_time` (`merchant_id`,`created_time`),
  KEY `idx_order_info_status_time` (`order_status`,`created_time`),
  KEY `idx_order_info_source_time` (`order_source`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单主表';
CREATE TABLE IF NOT EXISTS `order_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_id` bigint unsigned NOT NULL COMMENT '订单ID',
  `merchant_goods_id` bigint unsigned NOT NULL COMMENT '商家商品ID',
  `sku_id` bigint unsigned NOT NULL COMMENT 'SKU ID',
  `spu_name` varchar(150) NOT NULL COMMENT 'SPU名称快照',
  `sku_name` varchar(150) NOT NULL COMMENT 'SKU名称快照',
  `spec_text` varchar(255) NOT NULL COMMENT '规格快照',
  `quantity` int NOT NULL COMMENT '购买数量',
  `base_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '基础销售价快照',
  `member_price` decimal(12,2) DEFAULT NULL COMMENT '会员价快照',
  `customer_price` decimal(12,2) DEFAULT NULL COMMENT '客户专属价快照',
  `final_unit_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '最终单价',
  `final_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '最终金额',
  `cost_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '成本价快照',
  `profit_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '利润金额',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_order_item_order_id` (`order_id`),
  KEY `idx_order_item_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单明细表';
CREATE TABLE IF NOT EXISTS `order_item_adjust_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_id` bigint unsigned NOT NULL COMMENT '订单ID',
  `order_item_id` bigint unsigned NOT NULL COMMENT '订单明细ID',
  `old_quantity` int NOT NULL COMMENT '原数量',
  `new_quantity` int NOT NULL COMMENT '新数量',
  `old_final_unit_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '原最终单价',
  `new_final_unit_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '新最终单价',
  `old_final_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '原最终金额',
  `new_final_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '新最终金额',
  `operator_id` bigint unsigned DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(50) NOT NULL COMMENT '操作人名称',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_order_item_adjust_log_order_id` (`order_id`),
  KEY `idx_order_item_adjust_log_item_id` (`order_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单明细改单日志表';
CREATE TABLE IF NOT EXISTS `order_status_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_id` bigint unsigned NOT NULL COMMENT '订单ID',
  `old_status` varchar(30) DEFAULT NULL COMMENT '原状态',
  `new_status` varchar(30) NOT NULL COMMENT '新状态',
  `operation_type` varchar(30) NOT NULL COMMENT '操作类型',
  `operator_id` bigint unsigned DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(50) NOT NULL COMMENT '操作人名称',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_order_status_log_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单状态日志表';
CREATE TABLE IF NOT EXISTS `payment_record` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_id` bigint unsigned NOT NULL COMMENT '订单ID',
  `aftersale_id` bigint unsigned DEFAULT NULL COMMENT '售后单ID',
  `record_type` varchar(20) NOT NULL COMMENT '记录类型：PAY/REFUND',
  `pay_method` varchar(30) NOT NULL COMMENT '支付方式',
  `pay_amount` decimal(12,2) NOT NULL COMMENT '金额',
  `voucher_file_id` bigint unsigned DEFAULT NULL COMMENT '支付凭证附件ID',
  `transaction_no` varchar(100) DEFAULT NULL COMMENT '交易流水号',
  `pay_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '支付状态',
  `confirmed_by` bigint unsigned DEFAULT NULL COMMENT '确认人',
  `confirmed_time` datetime DEFAULT NULL COMMENT '确认时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_payment_record_order_id` (`order_id`),
  KEY `idx_payment_record_aftersale_id` (`aftersale_id`),
  KEY `idx_payment_record_type_status` (`record_type`,`pay_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='支付与退款记录表';
CREATE TABLE IF NOT EXISTS `platform_level_discount_rule` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `level_code` varchar(20) NOT NULL COMMENT '等级编码',
  `category_id` bigint unsigned NOT NULL COMMENT '分类ID',
  `discount_rate` decimal(5,2) NOT NULL COMMENT '折扣比例，如9.50表示9.5折',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_level_discount` (`level_code`,`category_id`),
  KEY `idx_platform_level_discount_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='平台会员等级折扣规则表';
CREATE TABLE IF NOT EXISTS `point_account` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `customer_id` bigint unsigned NOT NULL COMMENT '客户ID',
  `current_points` int NOT NULL DEFAULT '0' COMMENT '当前积分',
  `total_increase` int NOT NULL DEFAULT '0' COMMENT '累计增加',
  `total_decrease` int NOT NULL DEFAULT '0' COMMENT '累计扣减',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_point_account_customer_id` (`customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='积分账户表';
CREATE TABLE IF NOT EXISTS `point_record` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `point_account_id` bigint unsigned NOT NULL COMMENT '积分账户ID',
  `customer_id` bigint unsigned NOT NULL COMMENT '客户ID',
  `change_type` varchar(20) NOT NULL COMMENT '变动类型：INCREASE/DECREASE',
  `source_type` varchar(20) NOT NULL COMMENT '来源类型：ORDER/REFUND/REFERRAL/MANUAL',
  `source_id` bigint unsigned DEFAULT NULL COMMENT '来源业务ID',
  `change_points` int NOT NULL COMMENT '变动积分',
  `balance_after` int NOT NULL COMMENT '变动后余额',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_point_record_account_id` (`point_account_id`),
  KEY `idx_point_record_customer_time` (`customer_id`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='积分流水表';
CREATE TABLE IF NOT EXISTS `point_rule` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `rule_name` varchar(100) NOT NULL COMMENT '规则名称',
  `rule_type` varchar(30) NOT NULL COMMENT '规则类型：ORDER_REBATE/REFUND_DEDUCT/REFERRAL_BONUS',
  `value_type` varchar(20) NOT NULL COMMENT '取值类型：RATE/FIXED',
  `rule_value` decimal(10,2) NOT NULL COMMENT '规则值',
  `deduction_ratio` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '每积分可抵扣金额',
  `max_deduction_ratio` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单最高抵扣比例',
  `is_deduction_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否启用积分抵现',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_point_rule_type` (`rule_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='积分规则表';
CREATE TABLE IF NOT EXISTS `product_attachment` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `product_type` varchar(20) NOT NULL COMMENT '鍟嗗搧绫诲瀷锛歋PU/SKU',
  `product_id` bigint unsigned NOT NULL COMMENT '鍟嗗搧ID',
  `attachment_type` varchar(20) NOT NULL COMMENT '闄勪欢绫诲瀷锛欼MAGE/VIDEO/DOCUMENT',
  `file_id` bigint unsigned NOT NULL COMMENT 'file_storage琛↖D',
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '鎺掑簭鍙凤紙鍥剧墖椤哄簭锛',
  `is_primary` tinyint(1) NOT NULL DEFAULT '0' COMMENT '鏄?惁涓诲浘',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_product_attachment_product` (`product_type`,`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='鍟嗗搧闄勪欢琛';
CREATE TABLE IF NOT EXISTS `product_brand` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `brand_name` varchar(100) NOT NULL COMMENT '品牌名称',
  `brand_code` varchar(50) NOT NULL COMMENT '品牌编码',
  `logo_id` bigint unsigned DEFAULT NULL COMMENT '鍝佺墝Logo闄勪欢ID',
  `brand_desc` varchar(500) DEFAULT NULL COMMENT '鍝佺墝鎻忚堪',
  `origin` varchar(100) DEFAULT NULL COMMENT '浜у湴',
  `logo_file_id` bigint unsigned DEFAULT NULL COMMENT '品牌Logo附件ID',
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_product_brand_code` (`brand_code`),
  KEY `idx_product_brand_name` (`brand_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品品牌表';
CREATE TABLE IF NOT EXISTS `product_category` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `parent_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT '父分类ID',
  `category_name` varchar(100) NOT NULL COMMENT '分类名称',
  `category_code` varchar(50) NOT NULL COMMENT '分类编码',
  `icon_id` bigint unsigned DEFAULT NULL COMMENT '鍒嗙被鍥炬爣闄勪欢ID',
  `image_id` bigint unsigned DEFAULT NULL COMMENT '鍒嗙被鍥剧墖闄勪欢ID',
  `level_no` int NOT NULL DEFAULT '1' COMMENT '层级',
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_product_category_code` (`category_code`),
  KEY `idx_product_category_parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品分类表';
CREATE TABLE IF NOT EXISTS `product_sku` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `spu_id` bigint unsigned NOT NULL COMMENT 'SPU ID',
  `sku_code` varchar(50) NOT NULL COMMENT 'SKU编码',
  `sku_name` varchar(150) NOT NULL COMMENT 'SKU名称',
  `spec_text` varchar(255) NOT NULL COMMENT '规格描述',
  `image_ids` json DEFAULT NULL COMMENT 'SKU鍥剧墖ID鍒楄〃JSON',
  `specs` json DEFAULT NULL COMMENT '瑙勬牸灞炴?JSON锛堝?棰滆壊銆佸昂瀵革級',
  `weight` decimal(10,3) DEFAULT NULL COMMENT '閲嶉噺(kg)',
  `unit` varchar(20) DEFAULT NULL COMMENT '鍗曚綅',
  `barcode` varchar(64) DEFAULT NULL COMMENT '条码',
  `base_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '基础销售价',
  `cost_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '成本价',
  `stock_qty` int NOT NULL DEFAULT '0' COMMENT '当前库存',
  `safety_stock` int NOT NULL DEFAULT '0' COMMENT '安全库存',
  `sale_status` varchar(20) NOT NULL DEFAULT 'OFF' COMMENT '销售状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_product_sku_code` (`sku_code`),
  KEY `idx_product_sku_spu_id` (`spu_id`),
  KEY `idx_product_sku_sale_status` (`sale_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品SKU表';
CREATE TABLE IF NOT EXISTS `product_sku_spec` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `sku_id` bigint unsigned NOT NULL COMMENT 'SKU ID',
  `spec_name` varchar(50) NOT NULL COMMENT '瑙勬牸鍚嶇О锛堝?棰滆壊銆佸昂瀵革級',
  `spec_value` varchar(100) NOT NULL COMMENT '瑙勬牸鍊',
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '鎺掑簭鍙',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_product_sku_spec_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SKU瑙勬牸灞炴?琛';
CREATE TABLE IF NOT EXISTS `product_spu` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `supplier_id` bigint unsigned NOT NULL COMMENT '供应商ID',
  `brand_id` bigint unsigned NOT NULL COMMENT '品牌ID',
  `category_id` bigint unsigned NOT NULL COMMENT '分类ID',
  `spu_code` varchar(50) NOT NULL COMMENT 'SPU编码',
  `spu_name` varchar(150) NOT NULL COMMENT 'SPU名称',
  `unit_name` varchar(20) NOT NULL DEFAULT '件' COMMENT '单位',
  `main_image_id` bigint unsigned DEFAULT NULL COMMENT '涓诲浘闄勪欢ID',
  `image_ids` json DEFAULT NULL COMMENT '鍥剧墖ID鍒楄〃JSON',
  `sale_status` varchar(20) NOT NULL DEFAULT 'OFF' COMMENT '销售状态',
  `description` text COMMENT '商品描述',
  `detail_content` text COMMENT '璇︾粏鎻忚堪锛堝瘜鏂囨湰锛',
  `keywords` varchar(255) DEFAULT NULL COMMENT '鍏抽敭璇嶏紙SEO锛',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_product_spu_code` (`spu_code`),
  KEY `idx_product_spu_supplier_id` (`supplier_id`),
  KEY `idx_product_spu_brand_id` (`brand_id`),
  KEY `idx_product_spu_category_id` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品SPU表';
CREATE TABLE IF NOT EXISTS `product_stock_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sku_id` bigint unsigned NOT NULL COMMENT 'SKU ID',
  `change_type` varchar(20) NOT NULL COMMENT '变动类型：IN/OUT/ADJUST/RETURN',
  `change_qty` int NOT NULL COMMENT '变动数量',
  `before_qty` int NOT NULL COMMENT '变动前库存',
  `after_qty` int NOT NULL COMMENT '变动后库存',
  `biz_type` varchar(20) NOT NULL COMMENT '业务类型：ORDER/AFTERSALE/MANUAL',
  `biz_id` bigint unsigned DEFAULT NULL COMMENT '业务ID',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `operated_by` bigint unsigned DEFAULT NULL COMMENT '操作人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_product_stock_log_sku_id` (`sku_id`),
  KEY `idx_product_stock_log_biz` (`biz_type`,`biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='库存流水表';
CREATE TABLE IF NOT EXISTS `shipment_info` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_id` bigint unsigned NOT NULL COMMENT '订单ID',
  `ship_status` varchar(20) NOT NULL DEFAULT 'WAIT_SHIP' COMMENT '发货状态',
  `carrier_name` varchar(100) DEFAULT NULL COMMENT '承运公司',
  `tracking_no` varchar(100) DEFAULT NULL COMMENT '物流单号',
  `proof_file_id` bigint unsigned DEFAULT NULL COMMENT '签收或物流凭证附件ID',
  `ship_time` datetime DEFAULT NULL COMMENT '发货时间',
  `sign_time` datetime DEFAULT NULL COMMENT '签收时间',
  `logistics_remark` varchar(255) DEFAULT NULL COMMENT '物流备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shipment_info_order_id` (`order_id`),
  KEY `idx_shipment_info_status` (`ship_status`),
  KEY `idx_shipment_info_tracking_no` (`tracking_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='发货物流表';
CREATE TABLE IF NOT EXISTS `supplier_goods_authorization` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `supplier_id` bigint unsigned NOT NULL COMMENT '供应商ID',
  `merchant_id` bigint unsigned NOT NULL COMMENT '商家ID',
  `supplier_sku_id` bigint unsigned NOT NULL COMMENT '供应商SKU ID',
  `auth_status` varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '授权状态：ACTIVE/REVOKED',
  `authorized_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '授权成本价',
  `allocated_stock_qty` int NOT NULL DEFAULT '0' COMMENT '分配库存数量',
  `authorized_at` datetime DEFAULT NULL COMMENT '授权时间',
  `revoked_at` datetime DEFAULT NULL COMMENT '撤销时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_supplier_goods_authorization` (`supplier_id`,`merchant_id`,`supplier_sku_id`),
  KEY `idx_supplier_goods_authorization_merchant` (`merchant_id`),
  KEY `idx_supplier_goods_authorization_status` (`auth_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商商品授权表';
CREATE TABLE IF NOT EXISTS `supplier_info` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `member_id` bigint unsigned NOT NULL COMMENT '会员主体ID',
  `supplier_name` varchar(150) NOT NULL COMMENT '供应商名称',
  `qualification_file_id` bigint unsigned DEFAULT NULL COMMENT '资质附件ID',
  `contact_name` varchar(50) NOT NULL COMMENT '联系人',
  `contact_phone` varchar(20) NOT NULL COMMENT '联系电话',
  `supply_desc` text COMMENT '供货说明',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_supplier_info_member_id` (`member_id`),
  KEY `idx_supplier_info_supplier_name` (`supplier_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商信息表';
CREATE TABLE IF NOT EXISTS `sys_dict_data` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `dict_type_code` varchar(100) NOT NULL COMMENT '字典类型编码',
  `label` varchar(100) NOT NULL COMMENT '标签',
  `value` varchar(100) NOT NULL COMMENT '值',
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_sys_dict_data_type_code` (`dict_type_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典数据表';
CREATE TABLE IF NOT EXISTS `sys_dict_type` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `dict_name` varchar(100) NOT NULL COMMENT '字典名称',
  `dict_code` varchar(100) NOT NULL COMMENT '字典编码',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_dict_type_code` (`dict_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典类型表';
CREATE TABLE IF NOT EXISTS `sys_login_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `username` varchar(50) NOT NULL COMMENT '登录账号',
  `ip_address` varchar(64) DEFAULT NULL COMMENT 'IP地址',
  `login_status` varchar(20) NOT NULL COMMENT '登录结果：SUCCESS/FAIL',
  `login_message` varchar(255) DEFAULT NULL COMMENT '结果信息',
  `login_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_sys_login_log_user_id` (`user_id`),
  KEY `idx_sys_login_log_time` (`login_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='登录日志表';
CREATE TABLE IF NOT EXISTS `sys_menu` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `parent_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT '父菜单ID',
  `menu_name` varchar(100) NOT NULL COMMENT '菜单名称',
  `menu_type` varchar(20) NOT NULL COMMENT '类型：MENU/BUTTON',
  `path` varchar(200) DEFAULT NULL COMMENT '路由路径',
  `component` varchar(200) DEFAULT NULL COMMENT '前端组件路径',
  `permission_code` varchar(100) DEFAULT NULL COMMENT '权限编码',
  `icon` varchar(100) DEFAULT NULL COMMENT '图标',
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `visible` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否可见',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_sys_menu_parent_id` (`parent_id`),
  KEY `idx_sys_menu_type` (`menu_type`),
  KEY `idx_sys_menu_permission` (`permission_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜单与按钮表';
CREATE TABLE IF NOT EXISTS `sys_operation_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `username` varchar(50) NOT NULL COMMENT '操作账号',
  `module_name` varchar(100) NOT NULL COMMENT '模块名称',
  `business_type` varchar(50) NOT NULL COMMENT '业务类型',
  `request_uri` varchar(255) NOT NULL COMMENT '请求地址',
  `request_method` varchar(10) NOT NULL COMMENT '请求方式',
  `request_params` mediumtext COMMENT '请求参数',
  `operation_status` varchar(20) NOT NULL COMMENT '操作结果：SUCCESS/FAIL',
  `response_message` text COMMENT '响应信息',
  `error_stack` mediumtext COMMENT '异常堆栈',
  `operation_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人 ID',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人 ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0 否，1 是',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_sys_operation_log_user_id` (`user_id`),
  KEY `idx_sys_operation_log_time` (`operation_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作日志表';
CREATE TABLE IF NOT EXISTS `sys_role` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `role_name` varchar(50) NOT NULL COMMENT '角色名称',
  `role_code` varchar(50) NOT NULL COMMENT '角色编码',
  `data_scope` varchar(20) NOT NULL DEFAULT 'SELF' COMMENT '数据范围',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_role_code` (`role_code`),
  KEY `idx_sys_role_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色表';
CREATE TABLE IF NOT EXISTS `sys_role_menu` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `role_id` bigint unsigned NOT NULL COMMENT '角色ID',
  `menu_id` bigint unsigned NOT NULL COMMENT '菜单ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_role_menu` (`role_id`,`menu_id`),
  KEY `idx_sys_role_menu_menu_id` (`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色菜单关联表';
CREATE TABLE IF NOT EXISTS `sys_user` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `username` varchar(50) NOT NULL COMMENT '登录账号',
  `password` varchar(255) NOT NULL COMMENT '加密密码',
  `nick_name` varchar(50) NOT NULL COMMENT '用户昵称',
  `user_type` varchar(20) NOT NULL COMMENT '用户类型：ADMIN/MEMBER',
  `member_id` bigint unsigned DEFAULT NULL COMMENT '关联会员主体ID',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `register_source` varchar(30) DEFAULT NULL COMMENT '注册来源',
  `register_status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '注册状态',
  `last_active_identity_type` varchar(20) DEFAULT NULL COMMENT '最近活跃身份',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '状态：ENABLED/DISABLED',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_username` (`username`),
  KEY `idx_sys_user_member_id` (`member_id`),
  KEY `idx_sys_user_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统用户表';
CREATE TABLE IF NOT EXISTS `sys_user_menu` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `menu_id` bigint NOT NULL,
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_menu` (`user_id`,`menu_id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `sys_user_role` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `role_id` bigint unsigned NOT NULL COMMENT '角色ID',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_role` (`user_id`,`role_id`),
  KEY `idx_sys_user_role_role_id` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户角色关联表';
CREATE TABLE IF NOT EXISTS `user_identity_binding` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `identity_type` varchar(20) NOT NULL COMMENT '身份类型',
  `identity_ref_id` bigint unsigned NOT NULL COMMENT '身份主体ID',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLED' COMMENT '绑定状态',
  `is_default` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否默认身份',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_identity_binding` (`user_id`,`identity_type`,`identity_ref_id`),
  KEY `idx_user_identity_binding_status` (`status`),
  KEY `idx_user_identity_binding_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户身份绑定表';
